支持APM应用

diff --git a/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker b/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker
--- a/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker
+++ b/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker
@@ -125,7 +125,28 @@ fi
 
 log.info ""Skipping: $DESKTOP_FILE does not contain X-GXDE-KMREAPP=true""
 
+######## APM
 
+if  grep -q "X-APM-APPID=" "$DESKTOP_FILE"; then
+# 读取 X-APM-APPID 的值
+PKGNAME=$(grep -oP 'X-APM-APPID=\K.*' "$DESKTOP_FILE")
+
+if [ -z "$PKGNAME" ]; then
+    log.error "Error: X-APM-APPID= not found in $DESKTOP_FILE"
+    exit 1
+fi
+    apm autopurge "$PKGNAME" -y
+    exit_code=$?
+    if [ $exit_code -eq 0 ]; then
+        log.info "Uninstall successful: $PKGNAME in APM"
+        exit 0
+    else
+        log.error "Error: Uninstall failed for $PKGNAME in APM"
+        exit 1
+    fi
+    
+fi
+log.info ""Skipping: $DESKTOP_FILE does not contain X-APM-APPID""
 #############################################转发请求去ACE不同的卸载器
 
 
