1.6.2

diff --git a/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker b/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker
--- a/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker
+++ b/src/usr/libexec/gxde-app-uninstaller/gxde-app-uninstaller-worker
@@ -132,14 +132,21 @@ if  grep -q "X-APM-APPID=" "$DESKTOP_FILE"; then
 PKGNAME=$(grep -oP 'X-APM-APPID=\K.*' "$DESKTOP_FILE")
 
 if [ -z "$PKGNAME" ]; then
-    log.error "Error: X-APM-APPID= not found in $DESKTOP_FILE"
+    log.error "Error: X-APM-APPID= is empty in $DESKTOP_FILE"
     exit 1
 fi
-    apm autopurge "$PKGNAME" -y
+    amber-pm-debug dpkg -l | grep "^ii  $PKGNAME "
     exit_code=$?
     if [ $exit_code -eq 0 ]; then
-        log.info "Uninstall successful: $PKGNAME in APM"
-        exit 0
+        apm autopurge "$PKGNAME" -y
+            exit_code=$?
+            if [ $exit_code -eq 0 ]; then
+                log.info "Uninstall successful: $PKGNAME in APM"
+                exit 0
+            else
+                log.error "Error: Uninstall failed for $PKGNAME in APM"
+                exit 1
+            fi
     else
         apt autopurge "$PKGNAME" -y
         exit_code=$?
