support-package-name-uninstall

diff --git a/src/usr/libexec/gxde-app-uninstaller b/src/usr/libexec/gxde-app-uninstaller
--- a/src/usr/libexec/gxde-app-uninstaller
+++ b/src/usr/libexec/gxde-app-uninstaller
@@ -71,7 +71,7 @@ if [ "$UID" != "0" ]; then
 fi
 
 if [ "$#" -ne 2 ]; then
-    zenity --info --text="Usage: $0 desktop-name/file desktop-file-name/desktop-file-path" --width=400
+    zenity --info --text="Usage: $0 desktop-name/file/package-name desktop-file-name/desktop-file-path/package-name" --width=400
     exit 1
 fi
 
@@ -172,7 +172,7 @@ if [ "$1" = "desktop-name" ]; then
 
     # 验证是否为desktop文件
     if [ ! -e $ABSOLUTE_PATH_NO_REALPATH ]; then
-        zenity --error --text="$ABSOLUTE_PATH_NO_REALPATH does not exist. May have already been uninstalled. \n Use the command below to see output.\nsudo gxde-app-uninstaller-worker $ABSOLUTE_PATH_NO_REALPATH" --width=400
+        zenity --error --text="$ABSOLUTE_PATH_NO_REALPATH does not exist. May have already been uninstalled. \n Use the command below to see output.\nsudo gxde-app-uninstaller-worker desktop-file $ABSOLUTE_PATH_NO_REALPATH" --width=400
         exit -1
     fi
 
@@ -191,7 +191,7 @@ elif [ "$1" = "file" ]; then
 
     # 验证是否为desktop文件
     if [ ! -e $ABSOLUTE_PATH_NO_REALPATH ]; then
-        zenity --error --text="$ABSOLUTE_PATH_NO_REALPATH does not exist. May have already been uninstalled. \n Use the command below to see output.\nsudo gxde-app-uninstaller-worker $ABSOLUTE_PATH_NO_REALPATH" --width=400
+        zenity --error --text="$ABSOLUTE_PATH_NO_REALPATH does not exist. May have already been uninstalled. \n Use the command below to see output.\nsudo gxde-app-uninstaller-worker desktop-file $ABSOLUTE_PATH_NO_REALPATH" --width=400
         exit -1
     fi
 
@@ -199,6 +199,32 @@ elif [ "$1" = "file" ]; then
         zenity --error --text="Error: $ABSOLUTE_PATH_NO_REALPATH is not a desktop file." --width=400
         exit -1
     fi
+elif [[ "$1" = "package-name" ]];then
+if $(zenity --question --width=400 --text="${TRANSHELL_CONTENT_GOING_TO_UNINSTALL} $2.\n${TRANSHELL_CONTENT_UNINSTALL_USER_CONFIRM_TEXT}" ); then
+    (
+        gxde-app-uninstaller-worker package-name $2
+        ret=$?
+        if [ "$ret" != "0" ]; then
+            zenity --error --width 768 --text "$name ${TRANSHELL_CONTENT_UNINSTALL_FAILED}\n${TRANSHELL_CONTENT_USE_COMMAND_BELOW_TO_SEE_OUTPUT}\nsudo gxde-app-uninstaller-worker package-name $2"
+            exit -1
+        fi
+    ) &
+    cmd_pid=$!
+
+    (
+        while kill -0 $cmd_pid 2> /dev/null; do
+            sleep 1
+        done
+    ) | zenity --progress --text="${TRANSHELL_CONTENT_UNINSTALLING}" --pulsate --auto-close --no-cancel --width 400
+    wait $cmd_pid
+    notify-send -i gxde-deb-installer -a "${TRANSHELL_CONTENT_GXDE_APP_UNINSTALLER}" "${TRANSHELL_CONTENT_GXDE_APP_UNINSTALLER}" "$2 ${TRANSHELL_CONTENT_GXDE_APP_UNINSTALL_FINISHED}."
+
+
+fi
+
+exit
+
+
 else
     zenity --info --text="Usage: $0 desktop-name/file desktop-file-name/desktop-file-path" --width=400
     exit 1
@@ -215,7 +241,7 @@ fi
 
 if $(zenity --question --width=400 --text="${TRANSHELL_CONTENT_GOING_TO_UNINSTALL} $name.\n${TRANSHELL_CONTENT_UNINSTALL_USER_CONFIRM_TEXT}" ); then
     (
-        gxde-app-uninstaller-worker $ABSOLUTE_PATH_NO_REALPATH
+        gxde-app-uninstaller-worker desktop-file $ABSOLUTE_PATH_NO_REALPATH
         ret=$?
         if [ "$ret" != "0" ]; then
             zenity --error --width 768 --text "$name ${TRANSHELL_CONTENT_UNINSTALL_FAILED}\n${TRANSHELL_CONTENT_USE_COMMAND_BELOW_TO_SEE_OUTPUT}\nsudo gxde-app-uninstaller-worker $ABSOLUTE_PATH_NO_REALPATH"
diff --git a/src/usr/libexec/gxde-app-uninstaller-worker b/src/usr/libexec/gxde-app-uninstaller-worker
--- a/src/usr/libexec/gxde-app-uninstaller-worker
+++ b/src/usr/libexec/gxde-app-uninstaller-worker
@@ -54,8 +54,8 @@ log.error "Need to be run as root."
 exit 1
 fi
 # 检查参数个数
-if [ "$#" -ne 1 ]; then
-    log.info "Usage: $0 <desktop-file>"
+if [ "$#" -ne 2 ]; then
+    log.info "Usage: $0 desktop-file/package-name <desktop-file>/<packagename>"
     exit 1
 fi
 
@@ -63,13 +63,24 @@ fi
 # 清除先前的变量值
 unset ABSOLUTE_PATH PKGNAME_GUESS DPKG_LIST_FILE ACE_ENV_PATH
 
+if [[ "$1" = "package-name" ]];then
+            apt purge $2 -y
+		ret=$?
+		if [ "$ret" = "0" ];then
+			log.info "Operation succeeded."
+			exit 0
+		else
+			log.error "Operation failed."
+			exit $ret
+		fi
+elif [[ "$1" = "desktop-file" ]];then
 ####################################验证输入有效性
 # 保存并验证绝对路径
-ABSOLUTE_PATH=$(realpath $1)
-ABSOLUTE_PATH_NO_REALPATH=$1
+ABSOLUTE_PATH=$(realpath $2)
+ABSOLUTE_PATH_NO_REALPATH=$2
 
-log.debug "ABSOLUTE_PATH=$(realpath $1)"
-log.debug "ABSOLUTE_PATH_NO_REALPATH=$1"
+log.debug "ABSOLUTE_PATH=$(realpath $2)"
+log.debug "ABSOLUTE_PATH_NO_REALPATH=$2"
 # 验证是否为desktop文件
 	if [ ! -e $ABSOLUTE_PATH ];then
          echo -e "\e[31m[ERROR] $ABSOLUTE_PATH does not exist. May have already been uninstalled.  \e[0m"
@@ -175,4 +186,7 @@ PKGNAME_GUESS=$(basename "$ABSOLUTE_PATH" .desktop)
     log.error "Error: No matching package found."
     exit 1
 
-
+else
+log.error "Error: unknown option."
+exit 1
+fi
